[package]
name = "plexer"
version = "0.1.1"
authors = [ "emanuel" ]
edition = "2021"
description = "A Pattern-matching LEXER"
license = "MIT"
repository = "https://github.com/emsquid/plexer/"
keywords = ["lexer", "lexical", "analysis", "parser", "compiler"]

[dependencies]
regex = "1.10.2"
